### ISSUE TITLE
GXB-Core Release v1.0.200327

### ISSUE THREAD

**Issue by abyssal0** [gxchain/gxb-core#208]
upgrade to GXB-Core Release v1.0.200327
Download the latest release package, and unzip;
Stop witness_node;
Restart (with parameter --replay-blockchain --fast-replay).
But replay two days, my block still did not increase and stopped at 28835560

**Comment by lanhaoxiang** [comment]
This is caused by some backup  BP pushed forked blocks to the network during last upgrade, You may needs a block cut before replaying blockchain.

``` bash
./programs/witness_node/witness_node -x 28831000 --data-dir=trusted_node # change --data-dir if it's different from your start script
```

BTW, You can also use a snapshot at this time to quick start the node, without having to replay for 2 days.

snapshot address: [https://gxb-package.oss-cn-hangzhou.aliyuncs.com/gxb-core/object/object_database_28611771.tar.gz](https://gxb-package.oss-cn-hangzhou.aliyuncs.com/gxb-core/object/object_database_28611771.tar.gz)

Follow this document: [https://docs.gxchain.org/advanced/snapshot.html](https://docs.gxchain.org/advanced/snapshot.html)

**Comment by abyssal0** [comment]
thanks,I solved the problem according to this method
